all:
  children:
    vpn:
      hosts:
        vpn-server:
          ansible_host: 13.205.147.210
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10
    dcv:
      hosts:
        dcv-1:
          ansible_host: 10.20.2.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o IdentityFile=/home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -W %h:%p ubuntu@13.205.147.210'
        dcv-2:
          ansible_host: 10.20.2.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o IdentityFile=/home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -W %h:%p ubuntu@13.205.147.210'
        dcv-3:
          ansible_host: 10.20.2.12
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o IdentityFile=/home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -W %h:%p ubuntu@13.205.147.210'
        dcv-4:
          ansible_host: 10.20.2.13
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o IdentityFile=/home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -W %h:%p ubuntu@13.205.147.210'
        dcv-5:
          ansible_host: 10.20.2.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o IdentityFile=/home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/gokulupadhyayguragain/.ssh/dcv-improvised-key-20260425143759 -W %h:%p ubuntu@13.205.147.210'
